name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        - name: Checkout code
          uses: actions/checkout@v3
          with:
             fetch-depth: 0
             
        - name: Git Semantic Version
          uses: PaulHatch/semantic-version@v5.3.0
          with:
              major_pattern: "major:"
              minor_pattern: "feat:"
              format: "${major}.${minor}"
              id: version

        - name: Show Version
          env:
              NEW_VERSION: ${{ steps.version.outputs.version }}
          run: | 
              echo "$NEW_VERSION"

       

